use std::io::Write;
use std::path::Path;

fn main() {
    generate_playbook_manifest();
    tauri_build::build()
}

/// Scan `playbooks/` and generate a Rust manifest file so adding a playbook
/// is just dropping a `.md` file — no code changes needed.
fn generate_playbook_manifest() {
    let playbooks_dir = Path::new("playbooks");
    if !playbooks_dir.exists() {
        return;
    }

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("playbooks_manifest.rs");
    let mut f = std::fs::File::create(&dest).unwrap();

    // Collect all .md files: flat files and files inside one level of subdirectories.
    let mut flat_entries: Vec<String> = Vec::new(); // relative to playbooks/
    let mut folder_entries: Vec<String> = Vec::new(); // relative to playbooks/

    let entries = std::fs::read_dir(playbooks_dir).unwrap();
    for entry in entries.flatten() {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().to_string();

        if path.is_file() && name.ends_with(".md") && name != "TEMPLATE.md" {
            flat_entries.push(name);
        } else if path.is_dir() {
            // Scan subdirectory for .md files.
            if let Ok(sub_entries) = std::fs::read_dir(&path) {
                for sub in sub_entries.flatten() {
                    let sub_name = sub.file_name().to_string_lossy().to_string();
                    if sub_name.ends_with(".md") {
                        folder_entries.push(format!("{}/{}", name, sub_name));
                    }
                }
            }
        }
    }

    flat_entries.sort();
    folder_entries.sort();

    // Generate the Rust source.
    writeln!(f, "// Auto-generated by build.rs — do not edit.").unwrap();
    writeln!(f, "// To add a playbook, drop a .md file in playbooks/ or playbooks/<folder>/.").unwrap();
    writeln!(f).unwrap();

    // Flat playbooks.
    writeln!(f, "pub const BUILTIN_PLAYBOOKS: &[(&str, &str)] = &[").unwrap();
    for name in &flat_entries {
        writeln!(f, r#"    ("{name}", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/playbooks/{name}"))),"#).unwrap();
    }
    writeln!(f, "];").unwrap();
    writeln!(f).unwrap();

    // Folder playbooks.
    writeln!(f, "pub const BUILTIN_FOLDER_PLAYBOOKS: &[(&str, &str)] = &[").unwrap();
    for rel in &folder_entries {
        writeln!(f, r#"    ("{rel}", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/playbooks/{rel}"))),"#).unwrap();
    }
    writeln!(f, "];").unwrap();

    // Tell Cargo to rerun if any playbook file changes.
    println!("cargo:rerun-if-changed=playbooks");
}
